"""Adding cascade delete for all relationships v2

Revision ID: 00c3a4602c3b
Revises: 5221d221807b
Create Date: 2024-02-11 18:32:08.569184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c3a4602c3b'
down_revision: Union[str, None] = '5221d221807b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kanji_meanings_kanji_id_fkey', 'kanji_meanings', type_='foreignkey')
    op.create_foreign_key(None, 'kanji_meanings', 'kanji', ['kanji_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kanji_radicals_wk_radical_id_fkey', 'kanji_radicals', type_='foreignkey')
    op.drop_constraint('kanji_radicals_kanji_id_fkey', 'kanji_radicals', type_='foreignkey')
    op.create_foreign_key(None, 'kanji_radicals', 'wk_radicals', ['wk_radical_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kanji_radicals', 'kanji', ['kanji_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kanji_readings_kanji_id_fkey', 'kanji_readings', type_='foreignkey')
    op.create_foreign_key(None, 'kanji_readings', 'kanji', ['kanji_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kanji_readings', type_='foreignkey')
    op.create_foreign_key('kanji_readings_kanji_id_fkey', 'kanji_readings', 'kanji', ['kanji_id'], ['id'])
    op.drop_constraint(None, 'kanji_radicals', type_='foreignkey')
    op.drop_constraint(None, 'kanji_radicals', type_='foreignkey')
    op.create_foreign_key('kanji_radicals_kanji_id_fkey', 'kanji_radicals', 'kanji', ['kanji_id'], ['id'])
    op.create_foreign_key('kanji_radicals_wk_radical_id_fkey', 'kanji_radicals', 'wk_radicals', ['wk_radical_id'], ['id'])
    op.drop_constraint(None, 'kanji_meanings', type_='foreignkey')
    op.create_foreign_key('kanji_meanings_kanji_id_fkey', 'kanji_meanings', 'kanji', ['kanji_id'], ['id'])
    # ### end Alembic commands ###
