"""Adding level column into kanji table

Revision ID: 03b4de4d9752
Revises: 00c3a4602c3b
Create Date: 2024-02-11 19:14:37.442096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b4de4d9752'
down_revision: Union[str, None] = '00c3a4602c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanji', 'level')
    # ### end Alembic commands ###
