"""Add level column into the words table

Revision ID: 17376f5d8f89
Revises: 46b92b97f8be
Create Date: 2024-02-28 21:08:12.746581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17376f5d8f89'
down_revision: Union[str, None] = '46b92b97f8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'level')
    # ### end Alembic commands ###
