"""Wanikani radicals table rename

Revision ID: 30c5fc685eb9
Revises: d35ced49698f
Create Date: 2024-02-09 22:08:16.611699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c5fc685eb9'
down_revision: Union[str, None] = 'd35ced49698f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wk_radicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('mnemonic', sa.String(), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wk_radicals_id'), 'wk_radicals', ['id'], unique=False)
    op.drop_index('ix_wanikani_radicals_id', table_name='wanikani_radicals')
    op.drop_table('wanikani_radicals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanikani_radicals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mnemonic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wanikani_radicals_pkey')
    )
    op.create_index('ix_wanikani_radicals_id', 'wanikani_radicals', ['id'], unique=False)
    op.drop_index(op.f('ix_wk_radicals_id'), table_name='wk_radicals')
    op.drop_table('wk_radicals')
    # ### end Alembic commands ###
