"""Rename tables for word

Revision ID: 46b92b97f8be
Revises: a17ab2e17507
Create Date: 2024-02-28 17:57:45.376485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b92b97f8be'
down_revision: Union[str, None] = 'a17ab2e17507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_context_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('japanese', sa.String(), nullable=True),
    sa.Column('english', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_context_sentences_id'), 'word_context_sentences', ['id'], unique=False)
    op.create_table('word_meanings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_meanings_id'), 'word_meanings', ['id'], unique=False)
    op.create_table('word_use_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('japanese', sa.String(), nullable=True),
    sa.Column('english', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_use_patterns_id'), 'word_use_patterns', ['id'], unique=False)
    op.drop_index('ix_word_context_sentence_id', table_name='word_context_sentence')
    op.drop_table('word_context_sentence')
    op.drop_index('ix_word_meaning_id', table_name='word_meaning')
    op.drop_table('word_meaning')
    op.drop_index('ix_word_use_pattern_id', table_name='word_use_pattern')
    op.drop_table('word_use_pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_use_pattern',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('japanese', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('english', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='word_use_pattern_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='word_use_pattern_pkey')
    )
    op.create_index('ix_word_use_pattern_id', 'word_use_pattern', ['id'], unique=False)
    op.create_table('word_meaning',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='word_meaning_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='word_meaning_pkey')
    )
    op.create_index('ix_word_meaning_id', 'word_meaning', ['id'], unique=False)
    op.create_table('word_context_sentence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('japanese', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('english', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='word_context_sentence_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='word_context_sentence_pkey')
    )
    op.create_index('ix_word_context_sentence_id', 'word_context_sentence', ['id'], unique=False)
    op.drop_index(op.f('ix_word_use_patterns_id'), table_name='word_use_patterns')
    op.drop_table('word_use_patterns')
    op.drop_index(op.f('ix_word_meanings_id'), table_name='word_meanings')
    op.drop_table('word_meanings')
    op.drop_index(op.f('ix_word_context_sentences_id'), table_name='word_context_sentences')
    op.drop_table('word_context_sentences')
    # ### end Alembic commands ###
