"""Add tables for word data

Revision ID: 82ee3a122b06
Revises: d9faf31c5c14
Create Date: 2024-02-28 17:48:51.372225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ee3a122b06'
down_revision: Union[str, None] = 'd9faf31c5c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_context_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('japanese', sa.String(), nullable=True),
    sa.Column('english', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_context_sentence_id'), 'word_context_sentence', ['id'], unique=False)
    op.create_table('word_meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_meaning_id'), 'word_meaning', ['id'], unique=False)
    op.create_table('word_use_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('example_japanese', sa.String(), nullable=True),
    sa.Column('example_english', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_use_pattern_id'), 'word_use_pattern', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_use_pattern_id'), table_name='word_use_pattern')
    op.drop_table('word_use_pattern')
    op.drop_index(op.f('ix_word_meaning_id'), table_name='word_meaning')
    op.drop_table('word_meaning')
    op.drop_index(op.f('ix_word_context_sentence_id'), table_name='word_context_sentence')
    op.drop_table('word_context_sentence')
    # ### end Alembic commands ###
