"""Adding the url column for wk_radical table

Revision ID: 9e38c88a50a8
Revises: 86fb5e48bd39
Create Date: 2024-02-11 15:20:26.559091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e38c88a50a8'
down_revision: Union[str, None] = '86fb5e48bd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wk_radicals', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wk_radicals', 'url')
    # ### end Alembic commands ###
