"""Edit word table

Revision ID: b540f19995fa
Revises: 03b4de4d9752
Create Date: 2024-02-27 18:35:13.588104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b540f19995fa'
down_revision: Union[str, None] = '03b4de4d9752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kanji_url'), 'kanji', ['url'], unique=True)
    op.add_column('words', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_words_url'), 'words', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_url'), table_name='words')
    op.drop_column('words', 'url')
    op.drop_index(op.f('ix_kanji_url'), table_name='kanji')
    # ### end Alembic commands ###
