"""Adding source url column in kanji table

Revision ID: d2106f5c7fca
Revises: 7fb891d17008
Create Date: 2024-02-11 16:46:57.070779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2106f5c7fca'
down_revision: Union[str, None] = '7fb891d17008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanji', 'url')
    # ### end Alembic commands ###
