"""Adding radicals, Kanji and words table

Revision ID: d35ced49698f
Revises: 2ffa7d055770
Create Date: 2024-02-09 22:05:50.762641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35ced49698f'
down_revision: Union[str, None] = '2ffa7d055770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
